### ISSUE TITLE
guess_form Function

### ISSUE THREAD

**Issue by rsrobbins** [hyperreality/Poetry-Tools#4]
The guess_form function was giving me an error:

> AttributeError: 'list' object has no attribute 'replace'

I was able to fix this problem in the **poetics.py** file. It looks like the code was trying to tokenize the poem twice:

`poem = tokenize(tokenizedPoem)`

It did not need to be tokenized again:

`poem = tokenizedPoem`

**Comment by hyperreality** [comment]
Thanks, fixed.
