### ISSUE TITLE
Stress for words with different pronunciations

### ISSUE THREAD

**Issue by Tahlor** [hyperreality/Poetry-Tools#5]
Right now it's taking the "min" item from a list of pronunciations, which it is not obvious how this is defined (e.g. it's not even the pronunciation with fewer syllables--under this variant, "spring" returns 2 syllables). Do we know if the first pronunciation listed by CMU is the preferred one? In this case, it might be better to take the first element of the list.

**Comment by hyperreality** [comment]
You're right, min is an arbitrary way of selecting among multiple pronunciations, but I'm not sure that using the first pronunciation is officially any better. 'Spring' is an example of a word where the first provided pronunciation is better, however there are other words where the opposite seems to be the case. 

Nevertheless, choosing the first pronunciation is certainly clearer than picking the min, so I've accepted the change.
